ALTER TABLE shops
  ADD COLUMN IF NOT EXISTS receipt_show_logo TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS receipt_show_tax TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS receipt_show_discounts TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS receipt_show_cashier TINYINT(1) NOT NULL DEFAULT 1;
