ALTER TABLE shops
  ADD COLUMN IF NOT EXISTS login_email VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS login_password_hash VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS shop_code VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS owner_name VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS created_by_admin INT NULL,
  ADD COLUMN IF NOT EXISTS subscription_plan VARCHAR(50) NOT NULL DEFAULT 'starter',
  ADD COLUMN IF NOT EXISTS subscription_status VARCHAR(50) NOT NULL DEFAULT 'trial',
  ADD COLUMN IF NOT EXISTS subscription_start_date DATE NULL,
  ADD COLUMN IF NOT EXISTS subscription_expiry_date DATE NULL,
  ADD COLUMN IF NOT EXISTS monthly_fee DECIMAL(10,2) NOT NULL DEFAULT 0;

ALTER TABLE users
  MODIFY COLUMN email VARCHAR(255) NULL,
  MODIFY COLUMN role VARCHAR(50),
  ADD COLUMN IF NOT EXISTS username VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS shop_id INT NULL,
  ADD COLUMN IF NOT EXISTS permissions TEXT NULL,
  ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE sales
  ADD COLUMN IF NOT EXISTS created_by INT NULL,
  ADD COLUMN IF NOT EXISTS cashier_name VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS local_offline_id VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS sync_source VARCHAR(30) NOT NULL DEFAULT 'online';

CREATE UNIQUE INDEX IF NOT EXISTS unique_shop_login_email ON shops (login_email);
CREATE UNIQUE INDEX IF NOT EXISTS unique_shop_code ON shops (shop_code);
CREATE UNIQUE INDEX IF NOT EXISTS unique_shop_username ON users (shop_id, username);
CREATE UNIQUE INDEX IF NOT EXISTS unique_shop_offline_sale ON sales (shop_id, local_offline_id);
